name: Detekt_Actions


on:
  pull_request:
    branches:
      - main

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          repository: ${{ github.repository }}

      - name: Checkout JDK
        uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: '18'

      - name: Grand execute perm for gradlew
        run: chmod +x ./gradlew

      - name: BUILD run detekT
        run: ./gradlew detekt

      - name: BUILD app
        run: ./gradlew build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.3.4
        with:
          name: AndroidCICD.apk
          path: app/build/outputs/apk/debug/app-debug.apk
